name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 激活 Docker 服务
      run: |
        nohup sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended &
        while ! docker info &>/dev/null; do sleep 1; done

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/sharelatex:5.4.1-macos
